# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/jerofell/agsvm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/jerofell/agsvm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /users/jerofell/agsvm/CMakeFiles /users/jerofell/agsvm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /users/jerofell/agsvm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gossip_svm

# Build rule for target.
gossip_svm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gossip_svm
.PHONY : gossip_svm

# fast build rule for target.
gossip_svm/fast:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/build
.PHONY : gossip_svm/fast

#=============================================================================
# Target rules for targets named retin_algebra

# Build rule for target.
retin_algebra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 retin_algebra
.PHONY : retin_algebra

# fast build rule for target.
retin_algebra/fast:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/build
.PHONY : retin_algebra/fast

#=============================================================================
# Target rules for targets named retin_core

# Build rule for target.
retin_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 retin_core
.PHONY : retin_core

# fast build rule for target.
retin_core/fast:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/build
.PHONY : retin_core/fast

#=============================================================================
# Target rules for targets named retin_imcodec

# Build rule for target.
retin_imcodec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 retin_imcodec
.PHONY : retin_imcodec

# fast build rule for target.
retin_imcodec/fast:
	$(MAKE) -f CMakeFiles/retin_imcodec.dir/build.make CMakeFiles/retin_imcodec.dir/build
.PHONY : retin_imcodec/fast

#=============================================================================
# Target rules for targets named sparse_gossip_svm

# Build rule for target.
sparse_gossip_svm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sparse_gossip_svm
.PHONY : sparse_gossip_svm

# fast build rule for target.
sparse_gossip_svm/fast:
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/build
.PHONY : sparse_gossip_svm/fast

#=============================================================================
# Target rules for targets named test_vector_sparse

# Build rule for target.
test_vector_sparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_vector_sparse
.PHONY : test_vector_sparse

# fast build rule for target.
test_vector_sparse/fast:
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/build
.PHONY : test_vector_sparse/fast

src/common/math.o: src/common/math.cpp.o
.PHONY : src/common/math.o

# target to build an object file
src/common/math.cpp.o:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/math.cpp.o
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/math.cpp.o
.PHONY : src/common/math.cpp.o

src/common/math.i: src/common/math.cpp.i
.PHONY : src/common/math.i

# target to preprocess a source file
src/common/math.cpp.i:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/math.cpp.i
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/math.cpp.i
.PHONY : src/common/math.cpp.i

src/common/math.s: src/common/math.cpp.s
.PHONY : src/common/math.s

# target to generate assembly for a file
src/common/math.cpp.s:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/math.cpp.s
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/math.cpp.s
.PHONY : src/common/math.cpp.s

src/common/matrix_double.o: src/common/matrix_double.cpp.o
.PHONY : src/common/matrix_double.o

# target to build an object file
src/common/matrix_double.cpp.o:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/matrix_double.cpp.o
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/matrix_double.cpp.o
.PHONY : src/common/matrix_double.cpp.o

src/common/matrix_double.i: src/common/matrix_double.cpp.i
.PHONY : src/common/matrix_double.i

# target to preprocess a source file
src/common/matrix_double.cpp.i:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/matrix_double.cpp.i
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/matrix_double.cpp.i
.PHONY : src/common/matrix_double.cpp.i

src/common/matrix_double.s: src/common/matrix_double.cpp.s
.PHONY : src/common/matrix_double.s

# target to generate assembly for a file
src/common/matrix_double.cpp.s:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/matrix_double.cpp.s
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/matrix_double.cpp.s
.PHONY : src/common/matrix_double.cpp.s

src/common/matrix_float.o: src/common/matrix_float.cpp.o
.PHONY : src/common/matrix_float.o

# target to build an object file
src/common/matrix_float.cpp.o:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/matrix_float.cpp.o
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/matrix_float.cpp.o
.PHONY : src/common/matrix_float.cpp.o

src/common/matrix_float.i: src/common/matrix_float.cpp.i
.PHONY : src/common/matrix_float.i

# target to preprocess a source file
src/common/matrix_float.cpp.i:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/matrix_float.cpp.i
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/matrix_float.cpp.i
.PHONY : src/common/matrix_float.cpp.i

src/common/matrix_float.s: src/common/matrix_float.cpp.s
.PHONY : src/common/matrix_float.s

# target to generate assembly for a file
src/common/matrix_float.cpp.s:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/matrix_float.cpp.s
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/matrix_float.cpp.s
.PHONY : src/common/matrix_float.cpp.s

src/common/multithread.o: src/common/multithread.cpp.o
.PHONY : src/common/multithread.o

# target to build an object file
src/common/multithread.cpp.o:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/multithread.cpp.o
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/multithread.cpp.o
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/common/multithread.cpp.o
.PHONY : src/common/multithread.cpp.o

src/common/multithread.i: src/common/multithread.cpp.i
.PHONY : src/common/multithread.i

# target to preprocess a source file
src/common/multithread.cpp.i:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/multithread.cpp.i
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/multithread.cpp.i
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/common/multithread.cpp.i
.PHONY : src/common/multithread.cpp.i

src/common/multithread.s: src/common/multithread.cpp.s
.PHONY : src/common/multithread.s

# target to generate assembly for a file
src/common/multithread.cpp.s:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/multithread.cpp.s
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/multithread.cpp.s
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/common/multithread.cpp.s
.PHONY : src/common/multithread.cpp.s

src/common/utils.o: src/common/utils.cpp.o
.PHONY : src/common/utils.o

# target to build an object file
src/common/utils.cpp.o:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/utils.cpp.o
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/utils.cpp.o
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/common/utils.cpp.o
.PHONY : src/common/utils.cpp.o

src/common/utils.i: src/common/utils.cpp.i
.PHONY : src/common/utils.i

# target to preprocess a source file
src/common/utils.cpp.i:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/utils.cpp.i
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/utils.cpp.i
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/common/utils.cpp.i
.PHONY : src/common/utils.cpp.i

src/common/utils.s: src/common/utils.cpp.s
.PHONY : src/common/utils.s

# target to generate assembly for a file
src/common/utils.cpp.s:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/common/utils.cpp.s
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/common/utils.cpp.s
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/common/utils.cpp.s
.PHONY : src/common/utils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/gossip_svm.dir/build.make CMakeFiles/gossip_svm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/main_sparse.o: src/main_sparse.cpp.o
.PHONY : src/main_sparse.o

# target to build an object file
src/main_sparse.cpp.o:
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/main_sparse.cpp.o
.PHONY : src/main_sparse.cpp.o

src/main_sparse.i: src/main_sparse.cpp.i
.PHONY : src/main_sparse.i

# target to preprocess a source file
src/main_sparse.cpp.i:
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/main_sparse.cpp.i
.PHONY : src/main_sparse.cpp.i

src/main_sparse.s: src/main_sparse.cpp.s
.PHONY : src/main_sparse.s

# target to generate assembly for a file
src/main_sparse.cpp.s:
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/main_sparse.cpp.s
.PHONY : src/main_sparse.cpp.s

src/retin/toolbox/algebra/core.o: src/retin/toolbox/algebra/core.c.o
.PHONY : src/retin/toolbox/algebra/core.o

# target to build an object file
src/retin/toolbox/algebra/core.c.o:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/core.c.o
.PHONY : src/retin/toolbox/algebra/core.c.o

src/retin/toolbox/algebra/core.i: src/retin/toolbox/algebra/core.c.i
.PHONY : src/retin/toolbox/algebra/core.i

# target to preprocess a source file
src/retin/toolbox/algebra/core.c.i:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/core.c.i
.PHONY : src/retin/toolbox/algebra/core.c.i

src/retin/toolbox/algebra/core.s: src/retin/toolbox/algebra/core.c.s
.PHONY : src/retin/toolbox/algebra/core.s

# target to generate assembly for a file
src/retin/toolbox/algebra/core.c.s:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/core.c.s
.PHONY : src/retin/toolbox/algebra/core.c.s

src/retin/toolbox/algebra/matrix_double.o: src/retin/toolbox/algebra/matrix_double.c.o
.PHONY : src/retin/toolbox/algebra/matrix_double.o

# target to build an object file
src/retin/toolbox/algebra/matrix_double.c.o:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/matrix_double.c.o
.PHONY : src/retin/toolbox/algebra/matrix_double.c.o

src/retin/toolbox/algebra/matrix_double.i: src/retin/toolbox/algebra/matrix_double.c.i
.PHONY : src/retin/toolbox/algebra/matrix_double.i

# target to preprocess a source file
src/retin/toolbox/algebra/matrix_double.c.i:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/matrix_double.c.i
.PHONY : src/retin/toolbox/algebra/matrix_double.c.i

src/retin/toolbox/algebra/matrix_double.s: src/retin/toolbox/algebra/matrix_double.c.s
.PHONY : src/retin/toolbox/algebra/matrix_double.s

# target to generate assembly for a file
src/retin/toolbox/algebra/matrix_double.c.s:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/matrix_double.c.s
.PHONY : src/retin/toolbox/algebra/matrix_double.c.s

src/retin/toolbox/algebra/matrix_float.o: src/retin/toolbox/algebra/matrix_float.c.o
.PHONY : src/retin/toolbox/algebra/matrix_float.o

# target to build an object file
src/retin/toolbox/algebra/matrix_float.c.o:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/matrix_float.c.o
.PHONY : src/retin/toolbox/algebra/matrix_float.c.o

src/retin/toolbox/algebra/matrix_float.i: src/retin/toolbox/algebra/matrix_float.c.i
.PHONY : src/retin/toolbox/algebra/matrix_float.i

# target to preprocess a source file
src/retin/toolbox/algebra/matrix_float.c.i:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/matrix_float.c.i
.PHONY : src/retin/toolbox/algebra/matrix_float.c.i

src/retin/toolbox/algebra/matrix_float.s: src/retin/toolbox/algebra/matrix_float.c.s
.PHONY : src/retin/toolbox/algebra/matrix_float.s

# target to generate assembly for a file
src/retin/toolbox/algebra/matrix_float.c.s:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/matrix_float.c.s
.PHONY : src/retin/toolbox/algebra/matrix_float.c.s

src/retin/toolbox/algebra/pca.o: src/retin/toolbox/algebra/pca.cpp.o
.PHONY : src/retin/toolbox/algebra/pca.o

# target to build an object file
src/retin/toolbox/algebra/pca.cpp.o:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/pca.cpp.o
.PHONY : src/retin/toolbox/algebra/pca.cpp.o

src/retin/toolbox/algebra/pca.i: src/retin/toolbox/algebra/pca.cpp.i
.PHONY : src/retin/toolbox/algebra/pca.i

# target to preprocess a source file
src/retin/toolbox/algebra/pca.cpp.i:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/pca.cpp.i
.PHONY : src/retin/toolbox/algebra/pca.cpp.i

src/retin/toolbox/algebra/pca.s: src/retin/toolbox/algebra/pca.cpp.s
.PHONY : src/retin/toolbox/algebra/pca.s

# target to generate assembly for a file
src/retin/toolbox/algebra/pca.cpp.s:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/pca.cpp.s
.PHONY : src/retin/toolbox/algebra/pca.cpp.s

src/retin/toolbox/algebra/vector_double.o: src/retin/toolbox/algebra/vector_double.c.o
.PHONY : src/retin/toolbox/algebra/vector_double.o

# target to build an object file
src/retin/toolbox/algebra/vector_double.c.o:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_double.c.o
.PHONY : src/retin/toolbox/algebra/vector_double.c.o

src/retin/toolbox/algebra/vector_double.i: src/retin/toolbox/algebra/vector_double.c.i
.PHONY : src/retin/toolbox/algebra/vector_double.i

# target to preprocess a source file
src/retin/toolbox/algebra/vector_double.c.i:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_double.c.i
.PHONY : src/retin/toolbox/algebra/vector_double.c.i

src/retin/toolbox/algebra/vector_double.s: src/retin/toolbox/algebra/vector_double.c.s
.PHONY : src/retin/toolbox/algebra/vector_double.s

# target to generate assembly for a file
src/retin/toolbox/algebra/vector_double.c.s:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_double.c.s
.PHONY : src/retin/toolbox/algebra/vector_double.c.s

src/retin/toolbox/algebra/vector_float.o: src/retin/toolbox/algebra/vector_float.c.o
.PHONY : src/retin/toolbox/algebra/vector_float.o

# target to build an object file
src/retin/toolbox/algebra/vector_float.c.o:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_float.c.o
.PHONY : src/retin/toolbox/algebra/vector_float.c.o

src/retin/toolbox/algebra/vector_float.i: src/retin/toolbox/algebra/vector_float.c.i
.PHONY : src/retin/toolbox/algebra/vector_float.i

# target to preprocess a source file
src/retin/toolbox/algebra/vector_float.c.i:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_float.c.i
.PHONY : src/retin/toolbox/algebra/vector_float.c.i

src/retin/toolbox/algebra/vector_float.s: src/retin/toolbox/algebra/vector_float.c.s
.PHONY : src/retin/toolbox/algebra/vector_float.s

# target to generate assembly for a file
src/retin/toolbox/algebra/vector_float.c.s:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_float.c.s
.PHONY : src/retin/toolbox/algebra/vector_float.c.s

src/retin/toolbox/algebra/vector_short.o: src/retin/toolbox/algebra/vector_short.c.o
.PHONY : src/retin/toolbox/algebra/vector_short.o

# target to build an object file
src/retin/toolbox/algebra/vector_short.c.o:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_short.c.o
.PHONY : src/retin/toolbox/algebra/vector_short.c.o

src/retin/toolbox/algebra/vector_short.i: src/retin/toolbox/algebra/vector_short.c.i
.PHONY : src/retin/toolbox/algebra/vector_short.i

# target to preprocess a source file
src/retin/toolbox/algebra/vector_short.c.i:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_short.c.i
.PHONY : src/retin/toolbox/algebra/vector_short.c.i

src/retin/toolbox/algebra/vector_short.s: src/retin/toolbox/algebra/vector_short.c.s
.PHONY : src/retin/toolbox/algebra/vector_short.s

# target to generate assembly for a file
src/retin/toolbox/algebra/vector_short.c.s:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_short.c.s
.PHONY : src/retin/toolbox/algebra/vector_short.c.s

src/retin/toolbox/algebra/vector_uchar.o: src/retin/toolbox/algebra/vector_uchar.c.o
.PHONY : src/retin/toolbox/algebra/vector_uchar.o

# target to build an object file
src/retin/toolbox/algebra/vector_uchar.c.o:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_uchar.c.o
.PHONY : src/retin/toolbox/algebra/vector_uchar.c.o

src/retin/toolbox/algebra/vector_uchar.i: src/retin/toolbox/algebra/vector_uchar.c.i
.PHONY : src/retin/toolbox/algebra/vector_uchar.i

# target to preprocess a source file
src/retin/toolbox/algebra/vector_uchar.c.i:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_uchar.c.i
.PHONY : src/retin/toolbox/algebra/vector_uchar.c.i

src/retin/toolbox/algebra/vector_uchar.s: src/retin/toolbox/algebra/vector_uchar.c.s
.PHONY : src/retin/toolbox/algebra/vector_uchar.s

# target to generate assembly for a file
src/retin/toolbox/algebra/vector_uchar.c.s:
	$(MAKE) -f CMakeFiles/retin_algebra.dir/build.make CMakeFiles/retin_algebra.dir/src/retin/toolbox/algebra/vector_uchar.c.s
.PHONY : src/retin/toolbox/algebra/vector_uchar.c.s

src/retin/toolbox/core/SharedMatrix.o: src/retin/toolbox/core/SharedMatrix.cpp.o
.PHONY : src/retin/toolbox/core/SharedMatrix.o

# target to build an object file
src/retin/toolbox/core/SharedMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/SharedMatrix.cpp.o
.PHONY : src/retin/toolbox/core/SharedMatrix.cpp.o

src/retin/toolbox/core/SharedMatrix.i: src/retin/toolbox/core/SharedMatrix.cpp.i
.PHONY : src/retin/toolbox/core/SharedMatrix.i

# target to preprocess a source file
src/retin/toolbox/core/SharedMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/SharedMatrix.cpp.i
.PHONY : src/retin/toolbox/core/SharedMatrix.cpp.i

src/retin/toolbox/core/SharedMatrix.s: src/retin/toolbox/core/SharedMatrix.cpp.s
.PHONY : src/retin/toolbox/core/SharedMatrix.s

# target to generate assembly for a file
src/retin/toolbox/core/SharedMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/SharedMatrix.cpp.s
.PHONY : src/retin/toolbox/core/SharedMatrix.cpp.s

src/retin/toolbox/core/SharedMatrixDouble.o: src/retin/toolbox/core/SharedMatrixDouble.cpp.o
.PHONY : src/retin/toolbox/core/SharedMatrixDouble.o

# target to build an object file
src/retin/toolbox/core/SharedMatrixDouble.cpp.o:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/SharedMatrixDouble.cpp.o
.PHONY : src/retin/toolbox/core/SharedMatrixDouble.cpp.o

src/retin/toolbox/core/SharedMatrixDouble.i: src/retin/toolbox/core/SharedMatrixDouble.cpp.i
.PHONY : src/retin/toolbox/core/SharedMatrixDouble.i

# target to preprocess a source file
src/retin/toolbox/core/SharedMatrixDouble.cpp.i:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/SharedMatrixDouble.cpp.i
.PHONY : src/retin/toolbox/core/SharedMatrixDouble.cpp.i

src/retin/toolbox/core/SharedMatrixDouble.s: src/retin/toolbox/core/SharedMatrixDouble.cpp.s
.PHONY : src/retin/toolbox/core/SharedMatrixDouble.s

# target to generate assembly for a file
src/retin/toolbox/core/SharedMatrixDouble.cpp.s:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/SharedMatrixDouble.cpp.s
.PHONY : src/retin/toolbox/core/SharedMatrixDouble.cpp.s

src/retin/toolbox/core/sharedmem/matrix_reader.o: src/retin/toolbox/core/sharedmem/matrix_reader.cpp.o
.PHONY : src/retin/toolbox/core/sharedmem/matrix_reader.o

# target to build an object file
src/retin/toolbox/core/sharedmem/matrix_reader.cpp.o:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/sharedmem/matrix_reader.cpp.o
.PHONY : src/retin/toolbox/core/sharedmem/matrix_reader.cpp.o

src/retin/toolbox/core/sharedmem/matrix_reader.i: src/retin/toolbox/core/sharedmem/matrix_reader.cpp.i
.PHONY : src/retin/toolbox/core/sharedmem/matrix_reader.i

# target to preprocess a source file
src/retin/toolbox/core/sharedmem/matrix_reader.cpp.i:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/sharedmem/matrix_reader.cpp.i
.PHONY : src/retin/toolbox/core/sharedmem/matrix_reader.cpp.i

src/retin/toolbox/core/sharedmem/matrix_reader.s: src/retin/toolbox/core/sharedmem/matrix_reader.cpp.s
.PHONY : src/retin/toolbox/core/sharedmem/matrix_reader.s

# target to generate assembly for a file
src/retin/toolbox/core/sharedmem/matrix_reader.cpp.s:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/sharedmem/matrix_reader.cpp.s
.PHONY : src/retin/toolbox/core/sharedmem/matrix_reader.cpp.s

src/retin/toolbox/core/sharedmem/matrix_writer.o: src/retin/toolbox/core/sharedmem/matrix_writer.cpp.o
.PHONY : src/retin/toolbox/core/sharedmem/matrix_writer.o

# target to build an object file
src/retin/toolbox/core/sharedmem/matrix_writer.cpp.o:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/sharedmem/matrix_writer.cpp.o
.PHONY : src/retin/toolbox/core/sharedmem/matrix_writer.cpp.o

src/retin/toolbox/core/sharedmem/matrix_writer.i: src/retin/toolbox/core/sharedmem/matrix_writer.cpp.i
.PHONY : src/retin/toolbox/core/sharedmem/matrix_writer.i

# target to preprocess a source file
src/retin/toolbox/core/sharedmem/matrix_writer.cpp.i:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/sharedmem/matrix_writer.cpp.i
.PHONY : src/retin/toolbox/core/sharedmem/matrix_writer.cpp.i

src/retin/toolbox/core/sharedmem/matrix_writer.s: src/retin/toolbox/core/sharedmem/matrix_writer.cpp.s
.PHONY : src/retin/toolbox/core/sharedmem/matrix_writer.s

# target to generate assembly for a file
src/retin/toolbox/core/sharedmem/matrix_writer.cpp.s:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/sharedmem/matrix_writer.cpp.s
.PHONY : src/retin/toolbox/core/sharedmem/matrix_writer.cpp.s

src/retin/toolbox/core/sharedmem/shared_mem.o: src/retin/toolbox/core/sharedmem/shared_mem.cpp.o
.PHONY : src/retin/toolbox/core/sharedmem/shared_mem.o

# target to build an object file
src/retin/toolbox/core/sharedmem/shared_mem.cpp.o:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/sharedmem/shared_mem.cpp.o
.PHONY : src/retin/toolbox/core/sharedmem/shared_mem.cpp.o

src/retin/toolbox/core/sharedmem/shared_mem.i: src/retin/toolbox/core/sharedmem/shared_mem.cpp.i
.PHONY : src/retin/toolbox/core/sharedmem/shared_mem.i

# target to preprocess a source file
src/retin/toolbox/core/sharedmem/shared_mem.cpp.i:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/sharedmem/shared_mem.cpp.i
.PHONY : src/retin/toolbox/core/sharedmem/shared_mem.cpp.i

src/retin/toolbox/core/sharedmem/shared_mem.s: src/retin/toolbox/core/sharedmem/shared_mem.cpp.s
.PHONY : src/retin/toolbox/core/sharedmem/shared_mem.s

# target to generate assembly for a file
src/retin/toolbox/core/sharedmem/shared_mem.cpp.s:
	$(MAKE) -f CMakeFiles/retin_core.dir/build.make CMakeFiles/retin_core.dir/src/retin/toolbox/core/sharedmem/shared_mem.cpp.s
.PHONY : src/retin/toolbox/core/sharedmem/shared_mem.cpp.s

src/retin/toolbox/imcodec/ImageCodec.o: src/retin/toolbox/imcodec/ImageCodec.cpp.o
.PHONY : src/retin/toolbox/imcodec/ImageCodec.o

# target to build an object file
src/retin/toolbox/imcodec/ImageCodec.cpp.o:
	$(MAKE) -f CMakeFiles/retin_imcodec.dir/build.make CMakeFiles/retin_imcodec.dir/src/retin/toolbox/imcodec/ImageCodec.cpp.o
.PHONY : src/retin/toolbox/imcodec/ImageCodec.cpp.o

src/retin/toolbox/imcodec/ImageCodec.i: src/retin/toolbox/imcodec/ImageCodec.cpp.i
.PHONY : src/retin/toolbox/imcodec/ImageCodec.i

# target to preprocess a source file
src/retin/toolbox/imcodec/ImageCodec.cpp.i:
	$(MAKE) -f CMakeFiles/retin_imcodec.dir/build.make CMakeFiles/retin_imcodec.dir/src/retin/toolbox/imcodec/ImageCodec.cpp.i
.PHONY : src/retin/toolbox/imcodec/ImageCodec.cpp.i

src/retin/toolbox/imcodec/ImageCodec.s: src/retin/toolbox/imcodec/ImageCodec.cpp.s
.PHONY : src/retin/toolbox/imcodec/ImageCodec.s

# target to generate assembly for a file
src/retin/toolbox/imcodec/ImageCodec.cpp.s:
	$(MAKE) -f CMakeFiles/retin_imcodec.dir/build.make CMakeFiles/retin_imcodec.dir/src/retin/toolbox/imcodec/ImageCodec.cpp.s
.PHONY : src/retin/toolbox/imcodec/ImageCodec.cpp.s

src/retin/toolbox/imcodec/ImageCodecJPEG.o: src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.o
.PHONY : src/retin/toolbox/imcodec/ImageCodecJPEG.o

# target to build an object file
src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.o:
	$(MAKE) -f CMakeFiles/retin_imcodec.dir/build.make CMakeFiles/retin_imcodec.dir/src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.o
.PHONY : src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.o

src/retin/toolbox/imcodec/ImageCodecJPEG.i: src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.i
.PHONY : src/retin/toolbox/imcodec/ImageCodecJPEG.i

# target to preprocess a source file
src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.i:
	$(MAKE) -f CMakeFiles/retin_imcodec.dir/build.make CMakeFiles/retin_imcodec.dir/src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.i
.PHONY : src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.i

src/retin/toolbox/imcodec/ImageCodecJPEG.s: src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.s
.PHONY : src/retin/toolbox/imcodec/ImageCodecJPEG.s

# target to generate assembly for a file
src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.s:
	$(MAKE) -f CMakeFiles/retin_imcodec.dir/build.make CMakeFiles/retin_imcodec.dir/src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.s
.PHONY : src/retin/toolbox/imcodec/ImageCodecJPEG.cpp.s

src/retin/toolbox/imcodec/ImageCodecPNG.o: src/retin/toolbox/imcodec/ImageCodecPNG.cpp.o
.PHONY : src/retin/toolbox/imcodec/ImageCodecPNG.o

# target to build an object file
src/retin/toolbox/imcodec/ImageCodecPNG.cpp.o:
	$(MAKE) -f CMakeFiles/retin_imcodec.dir/build.make CMakeFiles/retin_imcodec.dir/src/retin/toolbox/imcodec/ImageCodecPNG.cpp.o
.PHONY : src/retin/toolbox/imcodec/ImageCodecPNG.cpp.o

src/retin/toolbox/imcodec/ImageCodecPNG.i: src/retin/toolbox/imcodec/ImageCodecPNG.cpp.i
.PHONY : src/retin/toolbox/imcodec/ImageCodecPNG.i

# target to preprocess a source file
src/retin/toolbox/imcodec/ImageCodecPNG.cpp.i:
	$(MAKE) -f CMakeFiles/retin_imcodec.dir/build.make CMakeFiles/retin_imcodec.dir/src/retin/toolbox/imcodec/ImageCodecPNG.cpp.i
.PHONY : src/retin/toolbox/imcodec/ImageCodecPNG.cpp.i

src/retin/toolbox/imcodec/ImageCodecPNG.s: src/retin/toolbox/imcodec/ImageCodecPNG.cpp.s
.PHONY : src/retin/toolbox/imcodec/ImageCodecPNG.s

# target to generate assembly for a file
src/retin/toolbox/imcodec/ImageCodecPNG.cpp.s:
	$(MAKE) -f CMakeFiles/retin_imcodec.dir/build.make CMakeFiles/retin_imcodec.dir/src/retin/toolbox/imcodec/ImageCodecPNG.cpp.s
.PHONY : src/retin/toolbox/imcodec/ImageCodecPNG.cpp.s

src/vector_sparse/MatrixSparse.o: src/vector_sparse/MatrixSparse.cpp.o
.PHONY : src/vector_sparse/MatrixSparse.o

# target to build an object file
src/vector_sparse/MatrixSparse.cpp.o:
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/vector_sparse/MatrixSparse.cpp.o
.PHONY : src/vector_sparse/MatrixSparse.cpp.o

src/vector_sparse/MatrixSparse.i: src/vector_sparse/MatrixSparse.cpp.i
.PHONY : src/vector_sparse/MatrixSparse.i

# target to preprocess a source file
src/vector_sparse/MatrixSparse.cpp.i:
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/vector_sparse/MatrixSparse.cpp.i
.PHONY : src/vector_sparse/MatrixSparse.cpp.i

src/vector_sparse/MatrixSparse.s: src/vector_sparse/MatrixSparse.cpp.s
.PHONY : src/vector_sparse/MatrixSparse.s

# target to generate assembly for a file
src/vector_sparse/MatrixSparse.cpp.s:
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/vector_sparse/MatrixSparse.cpp.s
.PHONY : src/vector_sparse/MatrixSparse.cpp.s

src/vector_sparse/VectorSparse.o: src/vector_sparse/VectorSparse.cpp.o
.PHONY : src/vector_sparse/VectorSparse.o

# target to build an object file
src/vector_sparse/VectorSparse.cpp.o:
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/vector_sparse/VectorSparse.cpp.o
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/vector_sparse/VectorSparse.cpp.o
.PHONY : src/vector_sparse/VectorSparse.cpp.o

src/vector_sparse/VectorSparse.i: src/vector_sparse/VectorSparse.cpp.i
.PHONY : src/vector_sparse/VectorSparse.i

# target to preprocess a source file
src/vector_sparse/VectorSparse.cpp.i:
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/vector_sparse/VectorSparse.cpp.i
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/vector_sparse/VectorSparse.cpp.i
.PHONY : src/vector_sparse/VectorSparse.cpp.i

src/vector_sparse/VectorSparse.s: src/vector_sparse/VectorSparse.cpp.s
.PHONY : src/vector_sparse/VectorSparse.s

# target to generate assembly for a file
src/vector_sparse/VectorSparse.cpp.s:
	$(MAKE) -f CMakeFiles/sparse_gossip_svm.dir/build.make CMakeFiles/sparse_gossip_svm.dir/src/vector_sparse/VectorSparse.cpp.s
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/vector_sparse/VectorSparse.cpp.s
.PHONY : src/vector_sparse/VectorSparse.cpp.s

src/vector_sparse/test.o: src/vector_sparse/test.cpp.o
.PHONY : src/vector_sparse/test.o

# target to build an object file
src/vector_sparse/test.cpp.o:
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/vector_sparse/test.cpp.o
.PHONY : src/vector_sparse/test.cpp.o

src/vector_sparse/test.i: src/vector_sparse/test.cpp.i
.PHONY : src/vector_sparse/test.i

# target to preprocess a source file
src/vector_sparse/test.cpp.i:
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/vector_sparse/test.cpp.i
.PHONY : src/vector_sparse/test.cpp.i

src/vector_sparse/test.s: src/vector_sparse/test.cpp.s
.PHONY : src/vector_sparse/test.s

# target to generate assembly for a file
src/vector_sparse/test.cpp.s:
	$(MAKE) -f CMakeFiles/test_vector_sparse.dir/build.make CMakeFiles/test_vector_sparse.dir/src/vector_sparse/test.cpp.s
.PHONY : src/vector_sparse/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gossip_svm"
	@echo "... rebuild_cache"
	@echo "... retin_algebra"
	@echo "... retin_core"
	@echo "... retin_imcodec"
	@echo "... sparse_gossip_svm"
	@echo "... test_vector_sparse"
	@echo "... src/common/math.o"
	@echo "... src/common/math.i"
	@echo "... src/common/math.s"
	@echo "... src/common/matrix_double.o"
	@echo "... src/common/matrix_double.i"
	@echo "... src/common/matrix_double.s"
	@echo "... src/common/matrix_float.o"
	@echo "... src/common/matrix_float.i"
	@echo "... src/common/matrix_float.s"
	@echo "... src/common/multithread.o"
	@echo "... src/common/multithread.i"
	@echo "... src/common/multithread.s"
	@echo "... src/common/utils.o"
	@echo "... src/common/utils.i"
	@echo "... src/common/utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main_sparse.o"
	@echo "... src/main_sparse.i"
	@echo "... src/main_sparse.s"
	@echo "... src/retin/toolbox/algebra/core.o"
	@echo "... src/retin/toolbox/algebra/core.i"
	@echo "... src/retin/toolbox/algebra/core.s"
	@echo "... src/retin/toolbox/algebra/matrix_double.o"
	@echo "... src/retin/toolbox/algebra/matrix_double.i"
	@echo "... src/retin/toolbox/algebra/matrix_double.s"
	@echo "... src/retin/toolbox/algebra/matrix_float.o"
	@echo "... src/retin/toolbox/algebra/matrix_float.i"
	@echo "... src/retin/toolbox/algebra/matrix_float.s"
	@echo "... src/retin/toolbox/algebra/pca.o"
	@echo "... src/retin/toolbox/algebra/pca.i"
	@echo "... src/retin/toolbox/algebra/pca.s"
	@echo "... src/retin/toolbox/algebra/vector_double.o"
	@echo "... src/retin/toolbox/algebra/vector_double.i"
	@echo "... src/retin/toolbox/algebra/vector_double.s"
	@echo "... src/retin/toolbox/algebra/vector_float.o"
	@echo "... src/retin/toolbox/algebra/vector_float.i"
	@echo "... src/retin/toolbox/algebra/vector_float.s"
	@echo "... src/retin/toolbox/algebra/vector_short.o"
	@echo "... src/retin/toolbox/algebra/vector_short.i"
	@echo "... src/retin/toolbox/algebra/vector_short.s"
	@echo "... src/retin/toolbox/algebra/vector_uchar.o"
	@echo "... src/retin/toolbox/algebra/vector_uchar.i"
	@echo "... src/retin/toolbox/algebra/vector_uchar.s"
	@echo "... src/retin/toolbox/core/SharedMatrix.o"
	@echo "... src/retin/toolbox/core/SharedMatrix.i"
	@echo "... src/retin/toolbox/core/SharedMatrix.s"
	@echo "... src/retin/toolbox/core/SharedMatrixDouble.o"
	@echo "... src/retin/toolbox/core/SharedMatrixDouble.i"
	@echo "... src/retin/toolbox/core/SharedMatrixDouble.s"
	@echo "... src/retin/toolbox/core/sharedmem/matrix_reader.o"
	@echo "... src/retin/toolbox/core/sharedmem/matrix_reader.i"
	@echo "... src/retin/toolbox/core/sharedmem/matrix_reader.s"
	@echo "... src/retin/toolbox/core/sharedmem/matrix_writer.o"
	@echo "... src/retin/toolbox/core/sharedmem/matrix_writer.i"
	@echo "... src/retin/toolbox/core/sharedmem/matrix_writer.s"
	@echo "... src/retin/toolbox/core/sharedmem/shared_mem.o"
	@echo "... src/retin/toolbox/core/sharedmem/shared_mem.i"
	@echo "... src/retin/toolbox/core/sharedmem/shared_mem.s"
	@echo "... src/retin/toolbox/imcodec/ImageCodec.o"
	@echo "... src/retin/toolbox/imcodec/ImageCodec.i"
	@echo "... src/retin/toolbox/imcodec/ImageCodec.s"
	@echo "... src/retin/toolbox/imcodec/ImageCodecJPEG.o"
	@echo "... src/retin/toolbox/imcodec/ImageCodecJPEG.i"
	@echo "... src/retin/toolbox/imcodec/ImageCodecJPEG.s"
	@echo "... src/retin/toolbox/imcodec/ImageCodecPNG.o"
	@echo "... src/retin/toolbox/imcodec/ImageCodecPNG.i"
	@echo "... src/retin/toolbox/imcodec/ImageCodecPNG.s"
	@echo "... src/vector_sparse/MatrixSparse.o"
	@echo "... src/vector_sparse/MatrixSparse.i"
	@echo "... src/vector_sparse/MatrixSparse.s"
	@echo "... src/vector_sparse/VectorSparse.o"
	@echo "... src/vector_sparse/VectorSparse.i"
	@echo "... src/vector_sparse/VectorSparse.s"
	@echo "... src/vector_sparse/test.o"
	@echo "... src/vector_sparse/test.i"
	@echo "... src/vector_sparse/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

